title: Clayton Hodges - GitHub Portfolio
description: Showcasing my experience in software development, problem-solving, and technical projects.
theme: jekyll-theme-slate

# Navigation
header_pages:
  - index.md
  - about.md
